all:
  is_secure: true
  credentials: SNSMember

registerInput:
  credentials: [[SNSRegisterBegin, SNSRegisterFinish]]

configComplete:
  is_secure: false

registerMobileToRegisterEnd:
  is_secure: false
