all:
  is_secure: true
  credentials: SNSMember

registerInput:
  credentials: [[SNSRegisterBegin, SNSRegisterFinish]]

configComplete:
  is_secure: false

changeLanguage:
  is_secure: false

registerMobileToRegisterEnd:
  credentials: SNSRegisterFinish

registerMobileToRegisterEndFinish:
  is_secure: false

